export enum MontessoriArea {
  PRACTICAL_LIFE = 'PRACTICAL_LIFE',
  SENSORIAL = 'SENSORIAL',
  LANGUAGE = 'LANGUAGE',
  MATHEMATICS = 'MATHEMATICS',
  CULTURAL = 'CULTURAL',
  ART = 'ART',
  MUSIC = 'MUSIC',
  MOVEMENT = 'MOVEMENT',
  SOCIAL_EMOTIONAL = 'SOCIAL_EMOTIONAL',
}
